image: python:3.11-slim

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONDONTWRITEBYTECODE: "1"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - python -V
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest -q --junitxml=junit.xml
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - junit.xml
    expire_in: 1 week
